---
title: 'EAE-1234: ECONOMIA DO SETOR PÚBLICO'
author: Pedro Forquesato<br/>Departamento de Economia<br/>Faculdade de Economia, Administração, Contabilidade e Atuária <br/>Universidade de São Paulo
date: "2026/1"
output:
  prettydoc::html_pretty:
    toc: yes
    theme: cayman
    urlcolor: red
  word_document: default
  html_document:
    toc: yes
    df_print: paged
  pdf_document: default
institute: Departamento de Economia<br/>Universidade de São Paulo
bibliography: ./esp_bib.bib
---

### Introdução

Nas economias modernas, mais de um terço (e às vezes mais da metade) da renda nacional é absorvida pelos governos na forma de impostos; os governos empregam um em cada cinco trabalhadores (média da OCDE) e, no Brasil, o consumo do governo representa quase 20% do PIB. É indiscutível, portanto, que estudar o papel do setor público na economia é essencial para compreender as sociedades modernas.

**Finanças públicas** é o estudo dos *gastos do governo* (políticas públicas) e da *receita do governo* (tributação). Neste curso, aplicamos as ferramentas da microeconomia para entender a melhor forma de implementar políticas públicas para melhorar o bem-estar social, bem como a melhor forma que os governos podem arrecadar receitas e como essa arrecadação impacta a economia.

### Objetivos de Aprendizagem

1. Reconhecer as principais fontes de intervenção governamental na economia, identificando os principais tipos de políticas públicas e formas de tributação e os problemas que elas enfrentam.
2. Compreender modelos microeconômicos de intervenção governamental na economia, conceitualizando o efeito de programas e impostos no comportamento de indivíduos e empresas.
3. Aplicar modelos e conceitos de finanças públicas a políticas do mundo real, prevendo de forma fundamentada e precisa as prováveis consequências de mudanças políticas.
4. Julgar a coerência lógica e a consistência empírica de argumentos sobre políticas públicas, avaliando criticamente os argumentos de economistas acadêmicos.
5. Formular argumentos consistentes e informados sobre o papel do governo, desenvolvendo argumentos em defesa da adoção de políticas e apresentando artigos com argumentos econômicos.

### Avaliação

1. Duas provas, cada uma valendo 30% da média do curso. (Objetivos de Aprendizagem 1 a 3.)
2. Uma apresentação em grupo de um artigo do JEP: 20% da média. (Objetivos de Aprendizagem 4 e 5.) [[Critérios de avaliação]](https://www.pedroforquesato.com/files/group_presentation_oral_rubric.pdf)
3. Um ensaio *individual* de 6500 palavras (artigo de opinião/jornal) sobre a aplicação da discussão do artigo do JEP ao Brasil: 20% da nota total. (Objetivos de Aprendizagem 3 e 5.)

Além disso, há uma lista de exercícios **opcional** que você pode entregar para receber até um ponto (**ponto extra**) na nota final. [[Lista de Exercícios]](https://www.pedroforquesato.com/files/eae1234_exercise_list_2025.pdf)

Todas as médias serão arredondadas para cima (em relação à nota final no Moodle) para uma casa decimal (**e apenas isso**).

### Qualidade de vida

Se você estiver tendo dificuldades: (i) se isso de alguma forma interferir na sua capacidade de fazer o curso, avise-me *antes do final do curso* e resolveremos algo; (ii) entre em contato com os serviços de saúde mental disponíveis na universidade:

1. [Programa ECOS: Serviço de Escuta em Saúde Mental](https://prip.usp.br/programa-ecos/)
2. [Sistema USP de Acolhimento, Registro e Responsabilização para assédio, violência, discriminações e outras violações de direitos humanos (SUA)](https://prip.usp.br/institucional/sistema-usp-de-acolhimento-sua/), também pelo telefone: (11) 3091-5001.

### Professor

Meu nome é Pedro Forquesato, sou professor associado no Departamento de Economia da FEA/USP e pesquisador no [LabPub](https://labpub.fea.usp.br/). Mais informações sobre mim podem ser encontradas em [meu site](https://www.pedroforquesato.com). Minha área de especialização é em microeconomia aplicada, com foco em economia do setor público. Em 2026, leciono este curso, EAE-1101: Princípios de Microeconomia e EAE-1301: Teoria dos Jogos (todos em nível de graduação).

### Contato

Para dúvidas específicas e individuais, envie-me um [e-mail](mailto:pforquesato@usp.br). Se quiser falar comigo pessoalmente, você pode agendar um horário usando o link disponível no Moodle. Minha sala é a 217 no FEA2.

Por favor, envie-me sempre e-mails claramente identificados, legíveis, **educados** e relativamente curtos. (Se o e-mail que você está escrevendo tiver mais de 2 parágrafos, pode ser melhor falar comigo pessoalmente.)

### Políticas e regulamentos

**Aulas.** As aulas serão às segundas-feiras das 9:20 às 11:00 e quartas-feiras das 7:30 às 09:10 na sala **??** do FEA 1.

**Comunicação.** Toda a comunicação oficial do curso será feita pelo [Moodle](https://edisciplinas.usp.br), incluindo listas, notas, frequência, avaliações e avisos. O curso pressupõe que o aluno acesse frequentemente a plataforma e verifique diariamente os e-mails recebidos.

**Frequência.** De acordo com as normas da USP, **a participação em 70% das aulas é obrigatória para aprovação no curso**. As faltas só serão abonadas mediante atestado médico emitido pelo HU/USP ([Portaria GR 3740/2007](http://leginf.usp.br/?portaria=portaria-gr-no-3740-de-29-de-marco-de-2007)).

Se o aluno perder **uma** prova (independentemente de atestado médico), poderá substituir a nota pela *segunda avaliação* sem necessidade de justificativa.

**Ética.** As provas são individuais e sem consulta, exceto quando indicado o contrário e nas exatas condições especificadas. Colar na prova resulta automaticamente em reprovação no curso. Os ensaios devem ser *inteiramente* originais. (Citações não são permitidas.) Listas podem ser resolvidas com a ajuda de colegas, mas devem ser redigidas individualmente. **O uso de IA (LLM) em qualquer atividade do curso é proibido e, se detectado, será punido assim como as outras violações éticas acima.**

Note que essas punições ocorrem sem prejuízo de processo administrativo conforme o [Código de Ética da USP](http://leginf.usp.br/?resolucao=resolucao-no-4871-de-22-de-outubro-de-2001-3).

**Revisões.** Juntamente com a correção da prova, enviarei o gabarito. Pedidos de revisão ([Artigo 81, §§1-2 do RG/USP](https://leginf.usp.br/?resolucao=consolidada-resolucao-no-3745-de-19-de-outubro-de-1990#t5)) devem ser acompanhados de uma explicação precisa e específica de onde a correção não estaria consistente com o gabarito e o porquê. Não há pedidos de revisão da nota final.

**Recuperação.** Alunos que tiverem mais de 70% de frequência e nota entre 3 e 5 ([Portaria CoG 3583/1989](https://leginf.usp.br/?resolucao=resolucao-cog-no-3583-de-29-de-setembro-de1989)) podem realizar uma segunda avaliação (reaval), tendo assim sua média final na disciplina como a média aritmética simples da média do curso e da nota da prova de recuperação.

**Outros.** Qualquer conflito com o professor que você não consiga (ou não queira) resolver pessoalmente, recomendo que entre em contato com a [Ouvidoria da FEA](https://www.fea.usp.br/fea/ouvidoria).

### Conteúdo programático e cronograma

Todas as datas no cronograma são **provisórias** e **sujeitas a alterações**.

1. **Economia normativa e análise de custo-benefício**: @atkinson, capítulo 11. @gruber, capítulo 8. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-1-normative.html)
2. **Princípios da intervenção governamental**: @gruber, capítulos 5, 6 e 7. @acemoglu. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-2-government.html)
3. **Saúde e educação**: @gruber, capítulos 11 e 15. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-3-health-education.html)

Primeira sessão de seminários: artigos [9], [2] e [5]: **13/04**.

4. **Previdência social**: @gruber, capítulos 12 e 13. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-4-social-security.html)
5. **Introdução à tributação**: @gruber, capítulo 18. @kleven. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-5-intro-taxation.html)
6. **Incidência tributária e peso morto**: @gruber, capítulos 19 e 20. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-6-incidence.html)

Segunda sessão de seminários: artigos [6], [12] e [1]: **27/04**.

Prova de meio-termo: **04/05**.

7. **Impostos sobre consumo**: @gruber, capítulos 19 e 20. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-7-consumption.html)
8. **Impostos sobre a renda do trabalho**: @gruber, capítulo 21. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-8-labor-income.html)
9. **Transferências e assistência social**: @gruber, cap. 17. @banerjee. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-9-social-assistance.html)

Terceira sessão de seminários: artigos [3], [8] e [7]: **18/05**.

10. **Tributação sobre poupança**: @gruber, capítulo 22. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-10-taxing-savings.html)
11. **Impostos sobre riqueza**: @gruber, capítulo 23. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-11-wealth-taxation.html)
12. **Impostos corporativos**: @gruber, capítulo 24. [[Slides]](https://www.pedroforquesato.com/eae1234/eae1234-12-corporate-taxes.html)

Quarta sessão de seminários: artigos [4], [10] e [11]: **22/06**.

Prova final: **29/06**.

Provas de anos anteriores (tenham em mente que ofertas anteriores alternaram entre português e inglês e que o programa da disciplina mudou ligeiramente ao longo dos anos, especialmente a ordem dos tópicos): <br> [[Prova de meio-termo 2022]](https://www.pedroforquesato.com/files/eae0310_prova_1_2022.pdf) [[Prova final 2022]](https://www.pedroforquesato.com/files/eae0310_prova_2_2022.pdf) <br> [[Prova de meio-termo 2023]](https://www.pedroforquesato.com/files/eae0310_prova_1_2023.pdf) [[Prova final 2023]](https://www.pedroforquesato.com/files/eae0310_prova_2_2023.pdf) <br>
[[Prova de meio-termo 2024]](https://www.pedroforquesato.com/files/eae1234_midterm_2024.pdf) [[Prova final 2024]](https://www.pedroforquesato.com/files/eae1234_final_2024.pdf) <br>
[[Prova de meio-termo 2025]](https://www.pedroforquesato.com/files/eae1234_midterm_2025.pdf) [[Prova final 2025]](https://www.pedroforquesato.com/files/eae1234_final_2025.pdf)

Prova de recuperação: **20/07**.

O prazo para entrega da lista opcional e dos ensaios pode ser verificado no [Moodle](https://edisciplinas.usp.br/).

### Apresentação em grupo

Os alunos se dividirão em 12 grupos e cada grupo escolherá um dos artigos abaixo para apresentar à turma em uma apresentação de 30 minutos.

1. Allcott, H., Lockwood, B. B., & Taubinsky, D. (2019). Should we tax sugar-sweetened beverages? An overview of theory and evidence. *Journal of Economic Perspectives*, 33(3), 202-227.
2. Auerbach, A. J. (2025). Public finance implications of economic inequality. *Journal of Economic Perspectives*, 39(2), 149-170.
4. Brockmeyer, A., Mascagni, G., Nair, V., Waseem, M., & Almunia, M. (2024). Does the value-added tax add value? Lessons using administrative data from a diverse set of countries. *Journal of Economic Perspectives*, 38(1), 107-132.
5. Chodorow-Reich, G., Zidar, O., & Zwick, E. (2024). Lessons from the biggest business tax cut in US history. *Journal of Economic Perspectives*, 38(3), 61-88.
7. Deming, D. J. (2022). Four facts about human capital. *Journal of Economic Perspectives*, 36(3), 75-102.
5. Ericson, K. M., & Sydnor, J. (2017). The questionable value of having a choice of levels of health insurance coverage. *Journal of Economic Perspectives*, 31(4), 51-72.
11. Herd, P., & Moynihan, D. (2025). Administrative burdens in the social safety net. *Journal of Economic Perspectives*, 39(1), 129-150.
5. Kleven, H., Landais, C., Munoz, M., & Stantcheva, S. (2020). Taxation and migration: evidence and policy implications. *Journal of Economic Perspectives*, 34(2), 119-142.
6. Gomez, M. (2025). Macro perspectives on income inequality. *Journal of Economic Perspectives*, 39(2), 127-148.
8. Scheuer, F., & Slemrod, J. (2021). Taxing our wealth. *Journal of Economic Perspectives*, 35(1), 207-230.
9. Slattery, C., & Zidar, O. (2020). Evaluating state and local business incentives. *Journal of Economic Perspectives*, 34(2), 90-118.
10. Woessmann, L. (2016). The importance of school systems: evidence from international differences in student achievement. *Journal of Economic Perspectives*, 30(3), 3-32.


### Bibliografia do curso

O livro-texto que seguimos de perto é *Public Finance and Public Policy*, de Jonathan Gruber. O curso baseia-se principalmente na 5ª edição, 2016. Os capítulos da bibliografia geralmente têm uma seção explicando o sistema público dos EUA: a leitura dessas seções é opcional. Também cobrimos durante o semestre três artigos de **leitura obrigatória** e um capítulo do livro clássico de 1980 de *Atkinson e Stiglitz* (veja o cronograma de leituras acima).

Além disso, é importante acompanhar os slides e as anotações de aula, pois trarei dados sobre o Brasil que não estão no livro (como todos os outros, o livro-texto é americano), além de algumas derivações e modelos que considero importantes.

#### Referências Obrigatórias
